version: "3.9"

services:
  mixedenergy-app-main:
    image: vicmrp/mixedenergy-app-main:nodejs22-1.0.0
    # build:
    #   context: ..
    #   dockerfile: .devcontainer/Dockerfile
    user: node
    command: sleep infinity
    stdin_open: true
    tty: true
    volumes:
      - ..:/usr/src/project

#   db:
#     image: postgres:15
#     restart: always
#     container_name: local-supabase-db
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_PASSWORD: example
#     volumes:
#       - db-data:/var/lib/postgresql/data

#   rest:
#     image: postgrest/postgrest
#     depends_on:
#       - db
#     ports:
#       - "3001:3000"
#     environment:
#       PGRST_DB_URI: "postgres://postgres:example@db:5432/supabase_app"
#       PGRST_DB_SCHEMA: "public"
#       PGRST_DB_ANON_ROLE: "anon"
#       PGRST_JWT_SECRET: "a-very-secret-jwt-token"
#       PGRST_DB_ROLE_SETTING: "true"

#   pgadmin:
#     image: dpage/pgadmin4:latest
#     container_name: pgadmin
#     depends_on:
#       - db
#     ports:
#       - "5050:80"    # Expose pgAdmin on http://localhost:5050
#     environment:
#       PGADMIN_DEFAULT_EMAIL: dev@example.com
#       PGADMIN_DEFAULT_PASSWORD: dev
#     # Optional volume if you want to persist pgAdmin settings
#     # volumes:
#     #   - pgadmin-data:/var/lib/pgadmin

# volumes:
#   db-data:
#   # pgadmin-data:
