version: "3.9"

services:
  mixedenergy-app-main:
    image: vicmrp/mixedenergy-app-main:nodejs22-1.1.0

    user: node
    command: sleep infinity
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"    # Next.js app
      - "9229:9229"    # Node Inspector port 1
      - "9230:9230"    # Node Inspector port 2 (Next.js may use this)
    volumes:
      - ..:/usr/src/project