version: "3.9"

services:
  mixedenergy-app-main:
    image: vicmrp/mixedenergy-app-main:nodejs22-1.1.0
    user: node
    command: sleep infinity
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
      - "9229:9229"
      - "9230:9230"
    volumes:
      - ..:/usr/src/project

  wordpress-db:
    image: mysql:5.7
    container_name: wordpress-db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: somewordpresspass
      MYSQL_ROOT_PASSWORD: somewordpressrootpass
    volumes:
      - wordpress_db_data:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - wordpress-db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: somewordpresspass
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped

volumes:
  wordpress_db_data:
  wordpress_data:
